targets:
  $default:
    builders:
      # Configure builders for code generation.
      json_serializable:
        generate_for:
          - lib/models/*.dart
      freezed:
        generate_for:
          - lib/models/*.dart
        options:
          any_map: true
          explicit_to_json: true

